export const chapters = [
  {
    id: 'game-overview',
    chapter: 1,
    title: 'Game Overview & High Concept',
    file: '01-game-overview.md',
    icon: 'Gamepad2',
    description: 'Game identity, target audience, competitive landscape',
  },
  {
    id: 'design-pillars',
    chapter: 2,
    title: 'Design Pillars',
    file: '02-design-pillars.md',
    icon: 'Columns3',
    description: 'Skill Over Luck, Meaningful Progression, Risk vs Reward',
  },
  {
    id: 'core-gameplay-loop',
    chapter: 3,
    title: 'Core Gameplay Loop & Meta Loop',
    file: '03-core-gameplay-loop.md',
    icon: 'RefreshCw',
    description: 'Session loop, meta progression, and gameplay flow',
  },
  {
    id: 'camera-and-controls',
    chapter: 4,
    title: 'Player Controls & Camera System',
    file: '04-camera-and-controls.md',
    icon: 'Camera',
    description: 'Movement, input handling, camera behavior',
  },
  {
    id: 'combat-system',
    chapter: 5,
    title: 'Combat System',
    file: '05-combat-system.md',
    icon: 'Swords',
    description: 'Weapons, damage affinities, defensive mechanics, combat flow',
  },
  {
    id: 'enemy-design',
    chapter: 6,
    title: 'Enemy Design System',
    file: '06-enemy-design.md',
    icon: 'Skull',
    description: 'Enemy types, behaviors, AI patterns, and stat scaling',
  },
  {
    id: 'boss-system',
    chapter: 7,
    title: 'Boss System',
    file: '07-boss-system.md',
    icon: 'Crown',
    description: 'Boss encounters, phases, mechanics, and rewards',
  },
  {
    id: 'level-and-stage-design',
    chapter: 8,
    title: 'Level & Stage Design',
    file: '08-level-and-stage-design.md',
    icon: 'Map',
    description: 'Maze generation, stage themes, environmental hazards',
  },
  {
    id: 'economy-loot-progression',
    chapter: 9,
    title: 'Economy, Loot & Progression',
    file: '09-economy-loot-progression.md',
    icon: 'Coins',
    description: 'Currency systems, loot drops, player progression',
  },
  {
    id: 'game-rules-fail-states',
    chapter: 10,
    title: 'Game Rules & Fail States',
    file: '10-game-rules-fail-states.md',
    icon: 'ShieldAlert',
    description: 'Win/lose conditions, lives, continues, and penalties',
  },
  {
    id: 'onboarding-tutorial',
    chapter: 11,
    title: 'Onboarding & Tutorial Flow',
    file: '11-onboarding-tutorial.md',
    icon: 'GraduationCap',
    description: 'New player experience, tutorials, and progressive disclosure',
  },
  {
    id: 'ui-hud-design',
    chapter: 12,
    title: 'UI / HUD Design',
    file: '12-ui-hud-design.md',
    icon: 'Layout',
    description: 'HUD layout, menus, screen flow, and UI components',
  },
  {
    id: 'audio-feedback',
    chapter: 13,
    title: 'Audio & Feedback Design',
    file: '13-audio-feedback.md',
    icon: 'Volume2',
    description: 'Sound effects, music, haptic feedback, and juice',
  },
  {
    id: 'visual-style-art',
    chapter: 14,
    title: 'Visual Style & Art Direction',
    file: '14-visual-style-art.md',
    icon: 'Palette',
    description: 'Art style, color palettes, asset guidelines',
  },
  {
    id: 'multiplayer-social',
    chapter: 15,
    title: 'Multiplayer & Social Features',
    file: '15-multiplayer-social.md',
    icon: 'Users',
    description: 'Co-op gameplay, matchmaking, social systems',
  },
  {
    id: 'monetization',
    chapter: 16,
    title: 'Monetization Design',
    file: '16-monetization.md',
    icon: 'DollarSign',
    description: 'Store, Battle Pass, cosmetics, pricing strategy',
  },
  {
    id: 'retention-live-ops',
    chapter: 17,
    title: 'Retention & Live Ops',
    file: '17-retention-live-ops.md',
    icon: 'TrendingUp',
    description: 'Daily rewards, events, seasons, player retention loops',
  },
  {
    id: 'analytics-metrics',
    chapter: 18,
    title: 'Analytics & Success Metrics',
    file: '18-analytics-metrics.md',
    icon: 'BarChart3',
    description: 'KPIs, tracking events, dashboards, success criteria',
  },
  {
    id: 'technical-architecture',
    chapter: 19,
    title: 'Technical Architecture',
    file: '19-technical-architecture.md',
    icon: 'Server',
    description: 'Client-server model, data stores, Luau architecture',
  },
  {
    id: 'accessibility',
    chapter: 20,
    title: 'Accessibility',
    file: '20-accessibility.md',
    icon: 'Accessibility',
    description: 'Accessibility features, settings, and inclusive design',
  },
  {
    id: 'risk-register',
    chapter: 21,
    title: 'Risk Register',
    file: '21-risk-register.md',
    icon: 'AlertTriangle',
    description: 'Known risks, mitigations, and contingency plans',
  },
  {
    id: 'appendix-a-damage-tables',
    chapter: 'A',
    title: 'Appendix A: Damage Tables',
    file: 'appendix-a-damage-tables.md',
    icon: 'Table',
    description: 'Full damage calculation tables and formulas',
  },
  {
    id: 'appendix-b-loot-tables',
    chapter: 'B',
    title: 'Appendix B: Loot Tables',
    file: 'appendix-b-loot-tables.md',
    icon: 'Package',
    description: 'Drop rates, loot pools, and reward tables',
  },
  {
    id: 'appendix-c-glossary',
    chapter: 'C',
    title: 'Appendix C: Glossary',
    file: 'appendix-c-glossary.md',
    icon: 'BookOpen',
    description: 'Definitions of key terms used throughout the GDD',
  },
];

export const chapterGroups = [
  {
    group: 'Core Design',
    chapters: ['game-overview', 'design-pillars', 'core-gameplay-loop'],
  },
  {
    group: 'Systems',
    chapters: ['camera-and-controls', 'combat-system', 'enemy-design', 'boss-system'],
  },
  {
    group: 'Content & Economy',
    chapters: ['level-and-stage-design', 'economy-loot-progression', 'game-rules-fail-states'],
  },
  {
    group: 'Player Experience',
    chapters: ['onboarding-tutorial', 'ui-hud-design', 'audio-feedback', 'visual-style-art'],
  },
  {
    group: 'Business & Growth',
    chapters: ['multiplayer-social', 'monetization', 'retention-live-ops', 'analytics-metrics'],
  },
  {
    group: 'Technical',
    chapters: ['technical-architecture', 'accessibility', 'risk-register'],
  },
  {
    group: 'Appendices',
    chapters: ['appendix-a-damage-tables', 'appendix-b-loot-tables', 'appendix-c-glossary'],
  },
];
